spring:
  application:
    name: pizza-ordering-backend
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: none

jwt:
  secret: ${JWT_SECRET:c4063cdf2e4e4acaa3eedd0eb5463c43e031f89ea887c7a248a8d6e92d8cd9cc}
  expiration: ${JWT_EXPIRATION:86400000} # 1 dia em milissegundos