spring:
  application:
    name: pizza-ordering-backend
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:pizzaria;DB_CLOSE_DELAY=-1
    username: user
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

jwt:
  secret: c4063cdf2e4e4acaa3eedd0eb5463c43e031f89ea887c7a248a8d6e92d8cd9cc
  expiration: 86400000 # 1 dia em milissegundos